Repository suzuki-shunsuke/tfcmt, pull requests merged in 2022-09, with the labels that each got.

#436 fix: github actions CI link domain
  pkg/platform/ci.go
Labels: bug

#451 fix: get an associated pull request number before adding pull request labels
  pkg/notifier/github/apply.go
  pkg/notifier/github/plan.go
Labels: bug

#454 docs: add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#378 fix: remove features to output environment variables for security
  pkg/config/complement.go
  pkg/config/complement_envsubst.go
  pkg/config/complement_template.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controller/controller.go
  pkg/domain/complement.go
  pkg/platform/ci.go
  pkg/platform/generic.go
  pkg/template/template.go
  pkg/terraform/template.go
Labels: breaking change
