Repository suzuki-shunsuke/tfcmt, pull requests merged in 2023-12, with the labels that each got.

#1062 fix: remove emojis from the end of lines
  example-with-destroy-and-result-labels.tfcmt.yaml
  pkg/config/config_test.go
  pkg/terraform/template.go
Labels: bug

#1073 Fix fenced code blocks
  pkg/terraform/template.go
Labels: bug

#1079 docs: Add READYFOR Platform Team to who-uses-tfcmt
  README.md
Labels: documentation, who-uses

#1091 feat: support the environment variable TFCMT_GITHUB_TOKEN
  pkg/config/config.go
  pkg/controller/controller.go
  pkg/notifier/github/client.go
  pkg/notifier/github/client_test.go
  pkg/notifier/github/comment_test.go
  pkg/notifier/github/commits_test.go
  pkg/notifier/github/github_test.go
  pkg/notifier/github/notify_test.go
Labels: enhancement
