Repository suzuki-shunsuke/tfcmt, pull requests merged in 2025-04, with the labels that each got.

#1733 fix: fix version command
  pkg/cli/app.go
Labels: bug

#1749 chore: Update suzuki-shunsuke/renovate-config to v3.2.1
  renovate.json5
Labels: update-suzuki-shunsuke-renovate-config-321

#1760 Update README.md
  README.md
Labels: documentation

#1761 docs: add Section-9 to who-uses-tfcmt
  README.md
Labels: documentation, who-uses

#1763 docs: add H2O Retailing Corp. to who-uses-tfcmt
  README.md
Labels: documentation, who-uses
